AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 500 #using early stopping
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 1e-6
MIN_DELTA: 0.001
PATIENCE: 20
RESTORE_BEST_WEIGHTS: True