artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia
  # source_URL: https://docs.google.com/uc?export=download&id=1e4liohQQtuqqh2Z1i8kavxJEwmLe_F5t
  # source_URL: https://drive.google.com/file/d/1e4liohQQtuqqh2Z1i8kavxJEwmLe_F5t/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


# data_transformation:
#   root_dir: artifacts/data_transformation
#   data_path: artifacts/data_ingestion/winequality-red.csv



# model_trainer:
#   root_dir: artifacts/model_trainer
#   train_data_path: artifacts/data_transformation/train.csv
#   test_data_path: artifacts/data_transformation/test.csv
#   model_name: model.joblib



# model_evaluation:
#   root_dir: artifacts/model_evaluation
#   test_data_path: artifacts/data_transformation/test.csv
#   model_path: artifacts/model_trainer/model.joblib
#   metric_file_name: artifacts/model_evaluation/metrics.json